name: slips
channels:
  - intel
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.12.0=py37hecd8cb5_0
  - aiodns=2.0.0=py_2
  - aiohttp=3.7.4=py37h9ed2024_1
  - argh=0.26.2=py37_0
  - astor=0.8.1=py37hecd8cb5_0
  - async-timeout=3.0.1=py37hecd8cb5_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h9ed2024_1003
  - c-ares=1.17.1=h9ed2024_0
  - ca-certificates=2021.7.5=hecd8cb5_1
  - certifi=2021.5.30=py37hecd8cb5_0
  - cffi=1.14.5=py37h2125817_0
  - chardet=3.0.4=py37hecd8cb5_1003
  - colorama=0.4.4=pyhd3eb1b0_0
  - coverage=5.5=py37h9ed2024_2
  - cryptography=3.4.7=py37h2fd3fbb_0
  - cycler=0.10.0=py_2
  - cython=0.29.22=py37h23ab428_0
  - daal=2020.3=intel_301
  - daal4py=2020.3=py37h861983e_1
  - decorator=4.4.2=pyhd3eb1b0_0
  - freetype=2.10.4=h4cff582_1
  - gast=0.2.2=py37_0
  - google-pasta=0.2.0=py_0
  - grpcio=1.36.1=py37h97de6d8_1
  - h5py=2.10.0=py37h0601b69_1
  - hdf5=1.10.6=hdbbcd12_0
  - icc_rt=2020.3=intel_301
  - importlib-metadata=3.7.3=py37hecd8cb5_1
  - importlib_metadata=1.5.0=py37_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2019.4=233
  - intelpython=2021.1.1=1
  - joblib=1.0.1=pyhd8ed1ab_0
  - keras=2.3.1=0
  - keras-applications=1.0.8=py_1
  - keras-base=2.3.1=py37_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.3.1=py37h23ab428_0
  - libcxx=10.0.0=1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libllvm10=10.0.1=h009f743_3
  - libpng=1.6.37=h7cec526_2
  - libprotobuf=3.14.0=h2842e9f_0
  - llvm-openmp=11.1.0=hda6cdc1_1
  - llvmlite=0.36.0=py37he4411ff_4
  - markdown=3.3.4=py37hecd8cb5_0
  - matplotlib-base=3.2.2=py37hddda452_1
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37h9ed2024_0
  - mkl_fft=1.3.0=py37ha059aab_0
  - mkl_random=1.1.1=py37h959d312_0
  - more-itertools=8.8.0=pyhd3eb1b0_0
  - multidict=5.1.0=py37h9ed2024_2
  - ncurses=6.2=h0a44026_1
  - numba=0.53.1=py37hb2f4e1b_0
  - numpy=1.19.2=py37h456fd55_0
  - numpy-base=1.19.2=py37hcfb5961_0
  - openssl=1.1.1k=h9ed2024_0
  - opt_einsum=3.1.0=py_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandas=1.2.3=py37hb2f4e1b_0
  - patsy=0.5.1=py_0
  - pip=21.0.1=py37hecd8cb5_0
  - pluggy=0.13.1=py37hecd8cb5_0
  - protobuf=3.14.0=py37h23ab428_1
  - py=1.10.0=pyhd3eb1b0_0
  - pycares=3.1.1=py37h9ed2024_0
  - pycparser=2.20=py_2
  - pyod=0.8.7=pyh44b312d_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py37hecd8cb5_0
  - pytest=6.2.4=py37hecd8cb5_2
  - python=3.7.10=h88f2d9e_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.7=1_cp37m
  - pytz=2021.1=pyhd3eb1b0_0
  - pyyaml=5.4.1=py37h9ed2024_1
  - readline=8.1=h9ed2024_0
  - scikit-learn=0.23.2=py37h72ef46a_5
  - scipy=1.6.2=py37h2515648_0
  - setuptools=52.0.0=py37hecd8cb5_0
  - six=1.15.0=py37hecd8cb5_0
  - slackclient=2.9.3=py37hecd8cb5_0
  - sqlite=3.35.3=hce871da_0
  - statsmodels=0.12.2=py37h183f225_0
  - tbb=2020.3=h879752b_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - tensorflow=2.0.0=mkl_py37hda344b4_0
  - tensorflow-base=2.0.0=mkl_py37h66b1bf0_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - termcolor=1.1.0=py37hecd8cb5_1
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hb0a8c7a_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.1=py37hf967b71_1
  - typing-extensions=3.7.4.3=hd3eb1b0_0
  - typing_extensions=3.7.4.3=pyh06a4308_0
  - tzlocal=2.1=py37_0
  - urllib3=1.26.4=pyhd3eb1b0_0
  - validators=0.18.2=pyhd3eb1b0_0
  - watchdog=1.0.2=py37h9ed2024_1
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wrapt=1.12.1=py37h1de35cc_1
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - yarl=1.6.3=py37h9ed2024_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - antlr4-python3-runtime==4.8
    - cabby==0.1.23
    - colorlog==5.0.1
    - dnspython==2.0.0
    - furl==2.1.2
    - idna==2.10
    - ipwhois==1.2.0
    - libtaxii==1.1.119
    - lxml==4.6.3
    - maxminddb==2.0.3
    - orderedmultidict==1.0.1
    - redis==3.5.3
    - requests==2.25.1
    - simplejson==3.17.2
    - stix2==2.1.0
    - stix2-patterns==1.3.2
prefix: ~/miniconda3/envs/slips
