Identity:
  GenerateNewKey: true

Server:
  port: 9008
  Host: 127.0.0.1
  DhtServerMode: true

Redis:
  Host: 127.0.0.1
  Port: 6644
  Tl2NlChannel: iris_internal

PeerDiscovery:
  DisableBootstrappingNodes: true
